In [1]:
import pandas as pd

# Load the Twitter dataset
df = pd.read_csv("../data/raw/twcs.csv")

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (2811774, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [2]:
# See all column names
print(df.columns.tolist())

['tweet_id', 'author_id', 'inbound', 'created_at', 'text', 'response_tweet_id', 'in_response_to_tweet_id']

In [3]:
# Find all support brands
brands = df[df["inbound"] == False]["author_id"].value_counts()

print("Number of brands:", len(brands))
brands.head(20)

Number of brands: 108

author_id
AmazonHelp         169840
AppleSupport       106860
Uber_Support        56270
SpotifyCares        43265
Delta               42253
Tesco               38573
AmericanAir         36764
TMobileHelp         34317
comcastcares        33031
British_Airways     29361
SouthwestAir        28977
VirginTrains        27817
Ask_Spectrum        25860
XboxSupport         24557
sprintcare          22381
hulu_support        21872
sainsburys          19466
GWRHelp             19364
AskPlayStation      19098
ChipotleTweets      18749
Name: count, dtype: int64

In [4]:
# Filter only Spotify support conversations

spotify = df[
    (df["author_id"] == "SpotifyCares") |
    (df["text"].str.contains("@SpotifyCares", case=False, na=False))
]

print("Spotify dataset shape:", spotify.shape)

spotify.head()

Spotify dataset shape: (74618, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
540,848,SpotifyCares,False,Tue Oct 31 22:28:16 +0000 2017,@115887 Hmm. Can you try restarting your devic...,849,850.0
541,849,115887,True,Tue Oct 31 23:36:20 +0000 2017,@SpotifyCares doesn’t work and i even tried de...,851,848.0
542,851,SpotifyCares,False,Tue Oct 31 23:39:03 +0000 2017,@115887 Could you send us a DM with your accou...,NaN,849.0
543,850,115887,True,Tue Oct 31 21:41:37 +0000 2017,@SpotifyCares Premium &amp; when i️ have it on...,848,852.0
544,852,SpotifyCares,False,Tue Oct 31 21:04:13 +0000 2017,"@115887 Thanks. Just to be sure, are you Free ...",850,853.0

In [5]:
# Count customer vs support tweets

spotify["inbound"].value_counts()

inbound
False    43265
True     31353
Name: count, dtype: int64

In [8]:
# Save cleaned Spotify dataset

spotify.to_csv("../data/processed/spotify_tweets.csv", index=False)

print("Saved successfully!")

Saved successfully!