In [5]:
import pandas as pd

golden = pd.read_csv("../data/golden_set.csv")

# Add empty labeling columns
golden["intent"] = ""
golden["escalate"] = ""
golden["notes"] = ""

# Save back to the same file
golden.to_csv("../data/golden_set.csv", index=False)

print("✅ Columns added successfully!")
golden.head()

✅ Columns added successfully!

,tweet_id,text,intent,escalate,notes
0,1301944,@SpotifyCares Best response ever! Me @ the use...,,,
1,1380867,@SpotifyCares Spotify Student + Hulu renews to...,,,
2,1790160,@SpotifyCares I just dumped the whole thing. I...,,,
3,1814781,"@SpotifyCares my band's ""related artists"" sect...",,,
4,254988,"@SpotifyCares Uh no....that""s not an answer. G...",,,

In [1]:
import pandas as pd

spotify = pd.read_csv("../data/processed/spotify_tweets.csv")

print(spotify.shape)
spotify.head()

(74618, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,848,SpotifyCares,False,Tue Oct 31 22:28:16 +0000 2017,@115887 Hmm. Can you try restarting your devic...,849,850.0
1,849,115887,True,Tue Oct 31 23:36:20 +0000 2017,@SpotifyCares doesn’t work and i even tried de...,851,848.0
2,851,SpotifyCares,False,Tue Oct 31 23:39:03 +0000 2017,@115887 Could you send us a DM with your accou...,NaN,849.0
3,850,115887,True,Tue Oct 31 21:41:37 +0000 2017,@SpotifyCares Premium &amp; when i️ have it on...,848,852.0
4,852,SpotifyCares,False,Tue Oct 31 21:04:13 +0000 2017,"@115887 Thanks. Just to be sure, are you Free ...",850,853.0

In [2]:
customers = spotify[spotify["inbound"] == True].copy()

print("Customer tweets:", customers.shape)

customers.head()

Customer tweets: (31353, 7)

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
1,849,115887,True,Tue Oct 31 23:36:20 +0000 2017,@SpotifyCares doesn’t work and i even tried de...,851,848.0
3,850,115887,True,Tue Oct 31 21:41:37 +0000 2017,@SpotifyCares Premium &amp; when i️ have it on...,848,852.0
5,853,115887,True,Tue Oct 31 19:57:59 +0000 2017,@SpotifyCares iphone 7+ and i have the most re...,852,854.0
8,857,115889,True,Wed Nov 01 07:40:06 +0000 2017,"@SpotifyCares Yes, multiple times. No changes....",859,856.0
10,858,115889,True,Tue Oct 31 22:01:30 +0000 2017,@SpotifyCares 2/2... and there is no way to ma...,856,860.0

In [3]:
sample = customers.sample(n=200, random_state=42)

sample = sample[["tweet_id", "text"]]

sample.head()

       tweet_id                                               text
29133   1301944  @SpotifyCares Best response ever! Me @ the use...
30437   1380867  @SpotifyCares Spotify Student + Hulu renews to...
39027   1790160  @SpotifyCares I just dumped the whole thing. I...
40121   1814781  @SpotifyCares my band's "related artists" sect...
5043     254988  @SpotifyCares Uh no....that"s not an answer. G...

In [4]:
sample.to_csv("../data/golden_set.csv", index=False)

print("Golden set created!")

Golden set created!